name: build

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    name: "Build (${{ matrix.cxx }}, ${{ matrix.os }})"

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            cc: clang-18
            cxx: clang++-18

          - os: ubuntu-24.04
            cc: clang-17
            cxx: clang++-17

          - os: ubuntu-24.04
            cc: clang-16
            cxx: clang++-16

          - os: ubuntu-24.04
            cc: gcc-14
            cxx: g++-14

          - os: ubuntu-24.04
            cc: gcc-13
            cxx: g++-13

          - os: ubuntu-24.04
            cc: gcc-12
            cxx: g++-12
    
          - os: windows-2022
            cc: cl
            cxx: cl
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Setup Windows
        if: runner.os == 'Windows'
        run: |
          choco install -y ninja

      - name: Set up Visual Studio shell on Windows
        uses: TheMrMilchmann/setup-msvc-dev@v3
        if: runner.os == 'Windows'
        with:
          arch: x64
           
      - name: Compiler version
        run: |
          ${{ matrix.cc }} --version
      
      - name: Build
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: |
          cmake --preset release -L
          cmake --build --preset release -v -- -k0
